name: thermonet
channels:
  - conda-forge
  - acellera
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - ld_impl_linux-64=2.44
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libuuid=2.41.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - pip=25.2
  - python=3.11.3
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - flatbuffers==25.9.23
      - gast==0.6.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - keras==2.15.0
      - libclang==18.1.1
      - markdown==3.9
      - markupsafe==3.0.3
      - ml-dtypes==0.3.2
      - msgpack==1.1.2
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scipy==1.16.2
      - six==1.17.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.2.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.14.2
